### ISSUE TITLE
Install command for react sdk in install an sdk' section of the documentation is incomplete

### ISSUE THREAD

**Issue by Jovells** [xmtp/docs-xmtp-org#43]
**Describe the bug**
Install command for the react sdk in the 'install an sdk' section of the documentation is incomplete. This is causing errors and requires digging to find the complete install command.
The right command can be found [here](https://github.com/xmtp/xmtp-web/tree/main/packages/react-sdk#install)

**To Reproduce**
1. Go to ['install an sdk' section of the documentation'](https://docs.xmtp.org/get-started/developer-quickstart#install-an-sdk)
2. Use the command there to install
3. Try to use the package in your app

**Expected behavior**
Install command in documentation should install all required packages

**Comment by jhaaaa** [comment]
Thank you so much for taking the time to file this bug, @Jovells - so sorry for this inconvenience. I'll get this fixed today!
